# Generated by Django 3.2.5 on 2022-12-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userDateOfBirth',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='mainApp/frontend/src/assets'),
        ),
    ]
